# syntax=docker/dockerfile:1
# Copyright 2026 Codesjoy
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG RUNTIME_IMAGE=gcr.io/distroless/base-debian12

FROM golang:1.26.4 AS build

ARG SERVICE
WORKDIR /src

COPY . .

RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN --mount=type=cache,target=/go/pkg/mod go mod download
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    test -n "${SERVICE}" && \
    CGO_ENABLED=0 go build -trimpath -o "/out/${SERVICE}" "./cmd/${SERVICE}"

FROM ${RUNTIME_IMAGE}

ARG SERVICE
WORKDIR /app

COPY --from=build "/out/${SERVICE}" "/app/server"
COPY --from=build "/src/configs/${SERVICE}.yaml" "/app/configs/${SERVICE}.yaml"

EXPOSE 8080
ENTRYPOINT ["/app/server"]
