// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package app

import (
	"log/slog"

	"github.com/codesjoy/sindri/internal/pkg/xgorm"
	"github.com/codesjoy/sindri/internal/sequence/biz"
	"github.com/codesjoy/sindri/internal/sequence/conf"
	"github.com/codesjoy/sindri/internal/sequence/data/gorm"
	"github.com/codesjoy/sindri/internal/sequence/metrics"
	"github.com/codesjoy/sindri/internal/sequence/service"
	"github.com/codesjoy/sindri/internal/sequence/task"
	"github.com/codesjoy/yggdrasil/v3"
	"github.com/codesjoy/yggdrasil/v3/app"
	"go.opentelemetry.io/otel/metric"
)

// Injectors from wire.go:

// InitializeBundle builds the complete sequence process bundle.
func InitializeBundle(rt app.Runtime, cfg *conf.Config) (*app.BusinessBundle, error) {
	config := cfg.Database
	database, err := xgorm.New(rt, config)
	if err != nil {
		return nil, err
	}
	nodeConfig := cfg.Node
	meter := provideAllocatorMeter(rt)
	allocatorConfig := &cfg.Allocator
	db := database.DB
	sequenceRepo := gorm.NewSequenceData(db)
	runtimeMemorySampler := metrics.NewRuntimeMemorySampler()
	logger := provideLogger(rt)
	allocator := biz.NewAllocator(allocatorConfig, sequenceRepo, runtimeMemorySampler, logger)
	metricsMetrics, err := metrics.NewMetrics(meter, allocator, runtimeMemorySampler)
	if err != nil {
		return nil, err
	}
	taskConfig := cfg.Ticker
	bizNodeConfig := &cfg.Node
	routeRepo := gorm.NewRouteModel(db)
	routeCache := biz.NewRouteCache()
	nodeManager := biz.NewNodeManager(bizNodeConfig, allocator, routeRepo, routeCache, logger)
	ticker := task.NewTicker(taskConfig, nodeManager)
	sequenceService := service.NewSequenceService(allocator, routeCache)
	businessBundle := provideBundle(database, nodeConfig, metricsMetrics, ticker, sequenceService)
	return businessBundle, nil
}

// wire.go:

func provideLogger(rt yggdrasil.Runtime) *slog.Logger {
	return rt.Logger()
}

func provideAllocatorMeter(rt yggdrasil.Runtime) metric.Meter {
	return rt.MeterProvider().Meter("github.com/codesjoy/sindri/sequence")
}
