// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"log/slog"

	"github.com/codesjoy/skuld/internal/pkg/xgorm"
	"github.com/codesjoy/skuld/internal/sequence/biz"
	"github.com/codesjoy/skuld/internal/sequence/conf"
	"github.com/codesjoy/skuld/internal/sequence/data/gorm"
	"github.com/codesjoy/skuld/internal/sequence/service"
	"github.com/codesjoy/skuld/internal/sequence/task"
	"github.com/codesjoy/yggdrasil/v3"
	"github.com/codesjoy/yggdrasil/v3/app"
)

// Injectors from wire.go:

// InitializeBundle builds the complete sequence process bundle.
func InitializeBundle(rt app.Runtime, cfg *conf.Config) (*app.BusinessBundle, error) {
	config := cfg.Database
	database, err := xgorm.New(rt, config)
	if err != nil {
		return nil, err
	}
	nodeConfig := cfg.Node
	taskConfig := cfg.Ticker
	bizNodeConfig := &cfg.Node
	allocatorConfig := &cfg.Allocator
	db := database.DB
	sequenceRepo := gorm.NewSequenceData(db)
	logger := provideLogger(rt)
	allocator := biz.NewAllocator(allocatorConfig, sequenceRepo, logger)
	routeRepo := gorm.NewRouteModel(db)
	routeCache := biz.NewRouteCache()
	nodeManager := biz.NewNodeManager(bizNodeConfig, allocator, routeRepo, routeCache, logger)
	ticker := task.NewTicker(taskConfig, nodeManager)
	sequenceService := service.NewSequenceService(allocator, routeCache)
	businessBundle := provideBundle(database, nodeConfig, ticker, sequenceService)
	return businessBundle, nil
}

// wire.go:

func provideLogger(rt yggdrasil.Runtime) *slog.Logger {
	return rt.Logger()
}
