syntax = "proto3";

package codesjoy.sindri.sequence.reason;

import "codesjoy/reason/v1/reason.proto";

option go_package = "github.com/codesjoy/sindri/gen/go/sequence/reason;reason";

enum Reason {
  option (codesjoy.reason.v1.default_reason) = 10000;

  REASON_UNSPECIFIED = 0;

  SEQUENCE_ALLOCATOR_PAUSED = 150 [(codesjoy.reason.v1.code) = UNAVAILABLE];
  SEQUENCE_SLOT_NOT_OWNER = 151 [(codesjoy.reason.v1.code) = FAILED_PRECONDITION];
  SEQUENCE_ROUTE_EXPIRED = 152 [(codesjoy.reason.v1.code) = FAILED_PRECONDITION];
  SEQUENCE_CAPACITY_EXHAUSTED = 153 [(codesjoy.reason.v1.code) = RESOURCE_EXHAUSTED];
  SEQUENCE_ROUTE_UNAVAILABLE = 154 [(codesjoy.reason.v1.code) = FAILED_PRECONDITION];
}
