// Copyright 2026 Codesjoy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package codesjoy.sindri.sequence.reason;

import "codesjoy/reason/v1/reason.proto";

option go_package = "github.com/codesjoy/sindri/gen/go/sequence/reason;reason";

enum Reason {
  option (codesjoy.reason.v1.default_reason) = 10000;

  REASON_UNSPECIFIED = 0;

  SEQUENCE_ALLOCATOR_PAUSED = 150 [(codesjoy.reason.v1.code) = UNAVAILABLE];
  SEQUENCE_SLOT_NOT_OWNER = 151 [(codesjoy.reason.v1.code) = FAILED_PRECONDITION];
  SEQUENCE_ROUTE_EXPIRED = 152 [(codesjoy.reason.v1.code) = FAILED_PRECONDITION];
  SEQUENCE_CAPACITY_EXHAUSTED = 153 [(codesjoy.reason.v1.code) = RESOURCE_EXHAUSTED];
  SEQUENCE_ROUTE_UNAVAILABLE = 154 [(codesjoy.reason.v1.code) = FAILED_PRECONDITION];
}
